contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - melange-autoupdate
    - melange
accounts:
  groups:
    - groupname: runner
      gid: 1000
  users:
    - username: runner
      uid: 1000
      gid: 1000
      homedir: ""
      shell: ""
  run-as: runner:runner
environment:
  PATH: /bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
entrypoint: 
  command:
    melange-autoupdate
