contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - wolfi-base
    - wolfi-baselayout
    - git
    - bash
    - gcc
    - melange-autoupdate
    - yq
    - jq
    - curl
    - aws-cli-2
work-dir: /work
environment:
  PATH: /bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
entrypoint: 
  command:
    melange-autoupdate
